print ("Welcome to the band name Generator!")
a = input("Which city did you grow up in ?\n")
print (a)
b = input ("What is the name of your pet?\n")
print ("Your band name could be " + a + " " + b)